"""alembic init

Revision ID: 7234322a035d
Revises: 
Create Date: 2026-08-17 07:43:20.530496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7234322a035d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('autor', sa.String(length=100), nullable=False),
    sa.Column('genero', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_livros_id'), 'livros', ['id'], unique=False)
    op.drop_table('denuncias')
    op.drop_table('participantes')
    op.drop_table('mensagens')
    op.drop_table('grupos')
    op.alter_column('biblioteca', 'usuario_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('biblioteca', 'livro_id',
               existing_type=mysql.VARCHAR(length=14),
               type_=sa.String(length=100),
               nullable=False)
    op.drop_index(op.f('idx_biblioteca_status'), table_name='biblioteca')
    op.drop_index(op.f('idx_biblioteca_usuario'), table_name='biblioteca')
    op.drop_index(op.f('usuario_id'), table_name='biblioteca')
    op.create_index(op.f('ix_biblioteca_id'), 'biblioteca', ['id'], unique=False)
    op.drop_index(op.f('email'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_index(op.f('email'), 'usuarios', ['email'], unique=True)
    op.drop_index(op.f('ix_biblioteca_id'), table_name='biblioteca')
    op.create_index(op.f('usuario_id'), 'biblioteca', ['usuario_id', 'livro_id'], unique=True)
    op.create_index(op.f('idx_biblioteca_usuario'), 'biblioteca', ['usuario_id'], unique=False)
    op.create_index(op.f('idx_biblioteca_status'), 'biblioteca', ['status_leitura'], unique=False)
    op.alter_column('biblioteca', 'livro_id',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=14),
               nullable=True)
    op.alter_column('biblioteca', 'usuario_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_table('grupos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('descricao', mysql.TEXT(), nullable=True),
    sa.Column('criador_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['criador_id'], ['usuarios.id'], name=op.f('grupos_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('mensagens',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grupo_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mensagem', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], name=op.f('mensagens_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('mensagens_ibfk_2'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('participantes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grupo_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], name=op.f('participantes_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('participantes_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('denuncias',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('denunciante_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('denunciado_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('motivo', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['denunciado_id'], ['usuarios.id'], name=op.f('denuncias_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['denunciante_id'], ['usuarios.id'], name=op.f('denuncias_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_livros_id'), table_name='livros')
    op.drop_table('livros')
    # ### end Alembic commands ###
